#!/bin/bash -x

terragrunt plan-all -detailed-exitcode

status=$?

if [[ ${status} == 2 ]]; then
    echo 'export CHANGES_PLANNED=1' >> $BASH_ENV
    exit 0
elif [[ ${status} == 1 ]]; then
    exit 1
else
    exit 0
fi
