#!/bin/sh -x

cd $HOME

echo test1234 > password

# Initialize the genesis.json file that will help you to bootstrap the network
gaiad init temp --chain-id testing2

# Create a key to hold your validator account
gaiacli keys add validator < password

# Add that key into the genesis.app_state.accounts array in the genesis file
# NOTE: this command lets you set the number of coins. Make sure this account has some coins
# with the genesis.app_state.stake.params.bond_denom denom, the default is STAKE
gaiad add-genesis-account $(gaiacli keys show validator -a) 1000000000stake,1000photino

# Generate the transaction that creates your validator
gaiad gentx --name validator < password

# Add the generated bonding transaction to the genesis file
gaiad collect-gentxs
