#!/bin/bash -e

curl --silent \
     --show-error \
     -X POST \
     --header "Content-Type: application/json" -d "{\"branch\": \"$CIRCLE_BRANCH\"}" "https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$WEBSITE_NAME/build?circle-token=$CIRCLE_COSMOS_TOKEN" > output.json

RESULT=`jq -r '.status' output.json`
MESSAGE=`jq -r '.message' output.json`

if [[ ${RESULT} == "null" ]] || [[ ${RESULT} -ne "200" ]]; then
    echo "CircleCI API call failed: $MESSAGE"
    exit 1
else
    echo "Website build started"
fi